export BLOCKSDSEXT		?= /opt/blocksds/external

ARM7ELF		?= $(BLOCKSDSEXT)/palib/sys/arm7_maxmod_dswifi.elf

ARM7ELF		:= $(BLOCKSDSEXT)/palib/sys/arm7_mp3.elf
BINDIRS		:= data
NITROFSDIR	:= filesystem

include ../../../Makefile_example
